panierfoyen:
    resource: "@PanierfoyenBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group    
    
kcfinder:
    resource: "@IkadocKCFinderBundle/Resources/config/routing.yml"
    prefix: /admin
    
kcfinder_browse:
    path:      /admin/kcfinder/browse.php
    defaults:  { _controller: IkadocKCFinderBundle:Proxy:proxy }   
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"