# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    panierfoyen.importcsv:
        class: PanierfoyenBundle\ImportCSV\ImportCSV
        arguments: ["@service_container"]
        
services:
    app_bundle.service.listener:
        class: PanierfoyenBundle\Listener\LoadDataListener
    tags:
        - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }        