services:
    panierfoyen.importcsv:
        class: PanierfoyenBundle\ImportCSV\ImportCSV
        arguments: ["@service_container"]
                
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
 
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
 
#    twig.extension.debug:
#        class: Twig_Extensions_Extension_Debug
#        tags:
#            - { name: twig.extension }
            
    app_bundle.service.listener:
        class: PanierfoyenBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }        
    panierfoyen.paginator:
        class: PanierfoyenBundle\Helper\paginator
        arguments: ["@service_container", "@router"]
